#!/bin/sh

set -e

case "$1" in
    remove|deconfigure)
        if command -v update-binfmts >/dev/null && test -r \
             /var/lib/binfmts/ksh; then
                 update-binfmts --package ksh93u+m --remove ksh \
                     /bin/ksh || true
        fi

        update-alternatives --remove ksh /bin/ksh93
        update-alternatives --remove shcomp /usr/bin/shcomp93

        # remove compatibility symlink if broken
        test '!' -h /usr/bin/ksh || test -e /usr/bin/ksh || rm -f /usr/bin/ksh
    ;;

    upgrade|failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

#DEBHELPER#

exit 0
